# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-26 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('second_name', models.CharField(db_index=True, max_length=150, verbose_name='Фамилия')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('preview', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Тизер')),
                ('text_post', markdownx.models.MarkdownxField(blank=True, db_index=True, verbose_name='Текст поста')),
                ('star', models.BooleanField(choices=[(True, 'Пост известной личности'), (False, 'Пост обычного пользователя')], default=False, verbose_name='Настройка поста')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('pictures', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на картинку')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
    ]
