# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-05 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190326_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='post',
            name='second_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Фамилия'),
        ),
    ]
