# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-19 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190505_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LinkWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_word', models.CharField(blank=True, db_index=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StopWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_word', models.TextField(blank=True, db_index=True, verbose_name='Стоп слова')),
            ],
        ),
        migrations.AddField(
            model_name='basicword',
            name='basic_word',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_word', to='mysite.LinkWord'),
        ),
    ]
