# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190519_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkword',
            old_name='link_word',
            new_name='word',
        ),
        migrations.RemoveField(
            model_name='basicword',
            name='basic_word',
        ),
        migrations.AddField(
            model_name='basicword',
            name='word',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='linkword',
            name='base_words',
            field=models.ManyToManyField(blank=True, db_index=True, max_length=500, related_name='link_words', to='mysite.BasicWord'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Заголовок'),
        ),
    ]
