# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-20 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20190520_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkword',
            name='word',
            field=models.CharField(blank=True, db_index=True, max_length=500, unique=True),
        ),
    ]
